export default {
  '13c21afe': [() => import(/* webpackChunkName: '13c21afe' */ '@site/docs/plugin.md'), '@site/docs/plugin.md', require.resolveWeak('@site/docs/plugin.md')],
  '17896441': [() => import(/* webpackChunkName: '17896441' */ '@theme/DocItem'), '@theme/DocItem', require.resolveWeak('@theme/DocItem')],
  '1be78505': [() => import(/* webpackChunkName: '1be78505' */ '@theme/DocPage'), '@theme/DocPage', require.resolveWeak('@theme/DocPage')],
  '201a6495': [() => import(/* webpackChunkName: '201a6495' */ '@site/docs/mockto.md'), '@site/docs/mockto.md', require.resolveWeak('@site/docs/mockto.md')],
  '3128966e': [() => import(/* webpackChunkName: '3128966e' */ '@site/docs/maskValue.md'), '@site/docs/maskValue.md', require.resolveWeak('@site/docs/maskValue.md')],
  '3847b3ea': [() => import(/* webpackChunkName: '3847b3ea' */ '@site/docs/setup.md'), '@site/docs/setup.md', require.resolveWeak('@site/docs/setup.md')],
  '68766071': [() => import(/* webpackChunkName: '68766071' */ '@site/docs/incubator.md'), '@site/docs/incubator.md', require.resolveWeak('@site/docs/incubator.md')],
  '6a55631f': [() => import(/* webpackChunkName: '6a55631f' */ '@site/docs/zucchini.md'), '@site/docs/zucchini.md', require.resolveWeak('@site/docs/zucchini.md')],
  '935f2afb': [() => import(/* webpackChunkName: '935f2afb' */ '~docs/default/version-current-metadata-prop-751.json'), '~docs/default/version-current-metadata-prop-751.json', require.resolveWeak('~docs/default/version-current-metadata-prop-751.json')],
  '9ed00105': [() => import(/* webpackChunkName: '9ed00105' */ '@site/docs/configuration.md'), '@site/docs/configuration.md', require.resolveWeak('@site/docs/configuration.md')],
  'a09c2993': [() => import(/* webpackChunkName: 'a09c2993' */ '@site/docs/introduction.md'), '@site/docs/introduction.md', require.resolveWeak('@site/docs/introduction.md')],
  'a2d5140b': [() => import(/* webpackChunkName: 'a2d5140b' */ 'D:\\code\\mocktomata\\website\\.docusaurus\\docusaurus-plugin-content-docs\\default\\plugin-route-context-module-100.json'), 'D:\\code\\mocktomata\\website\\.docusaurus\\docusaurus-plugin-content-docs\\default\\plugin-route-context-module-100.json', require.resolveWeak('D:\\code\\mocktomata\\website\\.docusaurus\\docusaurus-plugin-content-docs\\default\\plugin-route-context-module-100.json')],
  'b6766646': [() => import(/* webpackChunkName: 'b6766646' */ '@site/docs/spec.md'), '@site/docs/spec.md', require.resolveWeak('@site/docs/spec.md')],
  'ccda367d': [() => import(/* webpackChunkName: 'ccda367d' */ '@site/docs/komondor.md'), '@site/docs/komondor.md', require.resolveWeak('@site/docs/komondor.md')],};
